package com.alensgarage.worldcupfan2026;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 int red=Color.rgb(200,16,46), darkRed=Color.rgb(125,0,22), white=Color.WHITE; boolean darkMode=false; LinearLayout root,content,bottom; TextView title,sub; Data data; String myTeam="Croatia"; Handler handler=new Handler(); SharedPreferences prefs;
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("prefs",0);darkMode=prefs.getBoolean("dark",false);myTeam=prefs.getString("team","Croatia");data=new Data(this);build();showHome();}
 int bg(){return darkMode?Color.rgb(12,14,18):Color.rgb(247,247,247);} int cardColor(){return darkMode?Color.rgb(28,31,38):Color.WHITE;} int text(){return darkMode?Color.rgb(238,238,238):Color.rgb(28,28,34);} int muted(){return darkMode?Color.rgb(180,184,194):Color.rgb(90,90,96);} int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);} 
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg());setContentView(root);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(18),dp(18),dp(18),dp(12));GradientDrawable hg=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{darkRed,red,Color.rgb(220,0,52)});head.setBackground(hg);root.addView(head,new LinearLayout.LayoutParams(-1,dp(124)));title=tv("World Cup Fan 2026",26,Color.WHITE,1);title.setTypeface(Typeface.DEFAULT_BOLD);sub=tv("v2.1 • Premium Predictor • Offline World Cup Simulator",13,Color.WHITE,2);head.addView(title);head.addView(sub);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(12),dp(12),dp(12));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.HORIZONTAL);bottom.setPadding(dp(4),dp(4),dp(4),dp(4));bottom.setBackgroundColor(darkMode?Color.rgb(22,24,30):Color.WHITE);root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(66)));nav("Home");nav("Matches");nav("Groups");nav("Predict");nav("More");}
 void rebuild(){build();}
 void nav(String s){TextView b=tv(s,12,text(),1);b.setGravity(17);b.setTypeface(Typeface.DEFAULT_BOLD);GradientDrawable g=new GradientDrawable();g.setColor(darkMode?Color.rgb(35,38,46):Color.rgb(238,238,238));g.setCornerRadius(dp(12));b.setBackground(g);b.setOnClickListener(v->{if(s.equals("Home"))showHome();else if(s.equals("Matches"))showMatches();else if(s.equals("Groups"))showGroups();else if(s.equals("Predict"))showPredictor();else showMore();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);lp.setMargins(dp(3),0,dp(3),0);bottom.addView(b,lp);} 
 TextView tv(String s,int sp,int c,int lines){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);t.setPadding(dp(4),dp(3),dp(4),dp(3));if(lines>0)t.setMaxLines(lines);return t;} 
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{red,Color.rgb(225,0,52)});g.setCornerRadius(dp(20));b.setBackground(g);return b;}
 LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(14),dp(14),dp(14),dp(14));GradientDrawable gd=new GradientDrawable();gd.setColor(cardColor());gd.setCornerRadius(dp(22));gd.setStroke(dp(1),darkMode?Color.rgb(55,58,68):Color.rgb(228,228,228));l.setBackground(gd);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(12));content.addView(l,lp);return l;}
 void clear(String h,String s){title.setText(h);sub.setText(s);content.removeAllViews();root.setBackgroundColor(bg());}
 void showHome(){clear("World Cup Fan 2026","v2.1 • Premium Predictor • Offline World Cup Simulator");LinearLayout hero=card();hero.addView(tv("🔥 NEW v2.1 TEST BUILD",18,red,1));hero.addView(tv("Dark mode, share prediction, dream final, search matches and premium screen are now included.",14,muted(),3));LinearLayout c=card();c.addView(tv("⚽ Kick-off countdown",19,text(),1));TextView count=tv("",32,red,1);count.setTypeface(Typeface.DEFAULT_BOLD);c.addView(count);Runnable r=new Runnable(){public void run(){String d=daysTo("2026-06-11 21:00");count.setText(d+" "+(d.equals("1")?"day":"days")+" to opening match");handler.postDelayed(this,60000);}};r.run();LinearLayout mt=card();mt.addView(tv("⭐ My Team",20,text(),1));mt.addView(tv(myTeam+" • next matches, group table and path to final",16,darkMode?Color.WHITE:darkRed,2));Button open=btn("Open My Team");open.setOnClickListener(v->showMyTeam());mt.addView(open);LinearLayout p=card();p.addView(tv("🔥 Best selling feature",18,text(),1));p.addView(tv("Enter scores. The app calculates group standings, best third-placed teams and builds the knockout path.",15,muted(),4));Button bp=btn("Start Predictor");bp.setOnClickListener(v->showPredictor());p.addView(bp);}
 String daysTo(String date){try{Date d=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).parse(date);long diff=d.getTime()-System.currentTimeMillis();return String.valueOf(Math.max(0,diff/86400000));}catch(Exception e){return "0";}}
 EditText edit(int val){EditText e=new EditText(this);e.setHint("-");e.setText(val>=0?""+val:"");e.setTextSize(18);e.setInputType(2);e.setGravity(17);e.setTextColor(text());e.setHintTextColor(muted());return e;} int getInt(EditText e){try{return Integer.parseInt(e.getText().toString());}catch(Exception x){return -1;}}
 void showMatches(){clear("All Matches","Search, enter scores and save your tournament prediction");LinearLayout s=card();EditText q=new EditText(this);q.setHint("Search team or group, e.g. Croatia or A");q.setTextColor(text());q.setHintTextColor(muted());Button go=btn("Search");s.addView(q);s.addView(go);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);Runnable render=()->{list.removeAllViews();String term=q.getText().toString().toLowerCase(Locale.US).trim();for(Match m:data.matches){if(term.length()>0&&!m.home.toLowerCase(Locale.US).contains(term)&&!m.away.toLowerCase(Locale.US).contains(term)&&!m.group.toLowerCase(Locale.US).equals(term))continue;LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(14),dp(14),dp(14));GradientDrawable gd=new GradientDrawable();gd.setColor(cardColor());gd.setCornerRadius(dp(20));gd.setStroke(1,darkMode?Color.rgb(55,58,68):Color.rgb(225,225,225));c.setBackground(gd);LinearLayout.LayoutParams clp=new LinearLayout.LayoutParams(-1,-2);clp.setMargins(0,0,0,dp(10));list.addView(c,clp);TextView lab=tv(m.label(),17,text(),3);lab.setTypeface(Typeface.DEFAULT_BOLD);c.addView(lab);c.addView(tv(m.date+" • "+m.venue+" • Group "+m.group,13,muted(),2));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);EditText h=edit(m.homeGoals),a=edit(m.awayGoals);Button save=btn("Save");save.setOnClickListener(v->{m.homeGoals=getInt(h);m.awayGoals=getInt(a);data.save();toast("Result saved");showMatches();});row.addView(h,new LinearLayout.LayoutParams(0,dp(52),1));row.addView(a,new LinearLayout.LayoutParams(0,dp(52),1));row.addView(save,new LinearLayout.LayoutParams(dp(96),dp(52)));c.addView(row);}};go.setOnClickListener(v->render.run());render.run();}
 void showGroups(){clear("Groups","Automatic standings from entered results");Map<String,List<TeamRow>> map=data.standings();for(String g:data.groups){LinearLayout c=card();c.addView(tv("Group "+g,22,red,1));List<TeamRow> rows=map.get(g);for(int i=0;i<rows.size();i++){TeamRow r=rows.get(i);TextView line=tv((i+1)+". "+r.team+"  "+r.pts+" pts  "+r.gf+":"+r.ga+"  GD "+(r.gf-r.ga),15,text(),1);if(r.team.equals(myTeam))line.setTypeface(Typeface.DEFAULT_BOLD);c.addView(line);}}LinearLayout th=card();th.addView(tv("Best third-placed teams",19,text(),1));List<TeamRow> thirds=data.bestThirds();for(int i=0;i<thirds.size();i++)th.addView(tv((i+1)+". "+thirds.get(i).team+" (Group "+thirds.get(i).group+") • "+thirds.get(i).pts+" pts",14,i<8?red:muted(),1));}
 void showPredictor(){clear("Predictor","Fill scores, calculate tournament, share prediction");LinearLayout c=card();c.addView(tv("Your football bracket",21,text(),1));c.addView(tv("1) Enter scores in Matches.\n2) Groups update automatically.\n3) Top 2 teams + best 8 third teams go through.\n4) Share your prediction.",15,muted(),5));Button m=btn("Enter Match Scores");m.setOnClickListener(v->showMatches());c.addView(m);Button k=btn("View Knockout");k.setOnClickListener(v->showKnockout());c.addView(k);Button sh=btn("Share My Prediction");sh.setOnClickListener(v->sharePrediction());c.addView(sh);Button dream=btn("Dream Final");dream.setOnClickListener(v->showDreamFinal());c.addView(dream);Button reset=btn("Reset all scores");reset.setOnClickListener(v->{data.reset();showPredictor();});c.addView(reset);showGroupsPreview();}
 void showGroupsPreview(){LinearLayout c=card();c.addView(tv("Current qualified teams",18,text(),1));List<TeamRow> q=data.qualified();for(int i=0;i<Math.min(16,q.size());i++)c.addView(tv((i+1)+". "+q.get(i).team+" • Group "+q.get(i).group+" • "+q.get(i).pts+" pts",13,muted(),1));}
 void showDreamFinal(){clear("Dream Final","Pick your dream finalists and share it");LinearLayout c=card();Spinner a=new Spinner(this),b=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,data.teams);a.setAdapter(ad);b.setAdapter(ad);int pos=data.teams.indexOf(myTeam);if(pos>=0)a.setSelection(pos);c.addView(tv("Finalist 1",16,text(),1));c.addView(a);c.addView(tv("Finalist 2",16,text(),1));c.addView(b);Button share=btn("Share Dream Final");share.setOnClickListener(v->{String msg="🏆 My Dream Final: "+a.getSelectedItem()+" vs "+b.getSelectedItem()+"\nMade with World Cup Fan 2026";shareText(msg);});c.addView(share);}
 void showKnockout(){clear("Knockout Bracket","Round of 32 to Final");List<TeamRow> q=data.qualified();int games=16;for(String r:new String[]{"Round of 32","Round of 16","Quarter-finals","Semi-finals","Final"}){LinearLayout c=card();c.addView(tv("🏆 "+r,21,red,1));for(int i=0;i<games;i++){String a=(i*2)<q.size()?q.get(i*2).team:"TBD";String b=(i*2+1)<q.size()?q.get(i*2+1).team:"TBD";c.addView(tv("⚽ "+a+"  vs  "+b,15,text(),1));}games=Math.max(1,games/2);}}
 void showMyTeam(){clear("My Team","Personalized fan hub");LinearLayout c=card();c.addView(tv("Selected team: "+myTeam,22,red,1));Spinner sp=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,data.teams);sp.setAdapter(ad);int pos=data.teams.indexOf(myTeam);if(pos>=0)sp.setSelection(pos);c.addView(sp);Button save=btn("Save My Team");save.setOnClickListener(v->{myTeam=sp.getSelectedItem().toString();prefs.edit().putString("team",myTeam).apply();toast("My Team saved");showMyTeam();});c.addView(save);LinearLayout cm=card();cm.addView(tv("Matches",18,text(),1));for(Match m:data.matches)if(m.home.equals(myTeam)||m.away.equals(myTeam))cm.addView(tv(m.date+" • "+m.home+" vs "+m.away,14,muted(),2));}
 void showMore(){clear("More","Settings, premium and legal safety");LinearLayout c=card();Button my=btn("My Team");my.setOnClickListener(v->showMyTeam());c.addView(my);Button st=btn("Statistics");st.setOnClickListener(v->showStats());c.addView(st);Button ko=btn("Knockout");ko.setOnClickListener(v->showKnockout());c.addView(ko);Button dm=btn(darkMode?"Switch to Light Mode":"Switch to Dark Mode");dm.setOnClickListener(v->{darkMode=!darkMode;prefs.edit().putBoolean("dark",darkMode).apply();rebuild();showMore();});c.addView(dm);Button pr=btn("Premium / Pro Version");pr.setOnClickListener(v->showPremium());c.addView(pr);LinearLayout l=card();l.addView(tv("Version 2.1",18,red,1));l.addView(tv("Independent fan-made app. No official FIFA logo, no official crests, no player photos, no live streaming. Works offline and lets fans build predictions.",14,muted(),5));}
 void showPremium(){clear("Premium", "Pro features planned for Play Store");LinearLayout c=card();c.addView(tv("World Cup Fan 2026 Premium",22,red,2));c.addView(tv("• Unlimited saved predictions\n• Share prediction cards\n• Advanced knockout simulator\n• My Team reminders\n• No ads\n• Croatian + English",16,text(),8));Button b=btn("Premium coming soon");c.addView(b);}
 void showStats(){clear("Statistics","Calculated from entered results");int played=0,goals=0;Map<String,Integer> gf=new HashMap<>();for(Match m:data.matches)if(m.homeGoals>=0&&m.awayGoals>=0){played++;goals+=m.homeGoals+m.awayGoals;gf.put(m.home,gf.getOrDefault(m.home,0)+m.homeGoals);gf.put(m.away,gf.getOrDefault(m.away,0)+m.awayGoals);}LinearLayout c=card();c.addView(tv("Played matches: "+played,18,text(),1));c.addView(tv("Goals: "+goals,18,text(),1));String best="TBD";int max=-1;for(String t:gf.keySet())if(gf.get(t)>max){max=gf.get(t);best=t;}c.addView(tv("Best attack: "+best+" ("+Math.max(0,max)+")",18,red,1));}
 void sharePrediction(){String msg="⚽ My World Cup Fan 2026 prediction\n\nMy team: "+myTeam+"\nQualified teams:";List<TeamRow> q=data.qualified();for(int i=0;i<Math.min(8,q.size());i++)msg+="\n"+(i+1)+". "+q.get(i).team;msg+="\n\nMade with World Cup Fan 2026";shareText(msg);} void shareText(String msg){Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_TEXT,msg);startActivity(Intent.createChooser(send,"Share"));} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 static class Match{String group,home,away,date,venue;int homeGoals=-1,awayGoals=-1;Match(String g,String h,String a,String d,String v){group=g;home=h;away=a;date=d;venue=v;}String label(){return home+"  "+(homeGoals>=0?homeGoals:"-")+" : "+(awayGoals>=0?awayGoals:"-")+"  "+away;}}
 static class TeamRow{String group,team;int pts,gf,ga,w,d,l;TeamRow(String g,String t){group=g;team=t;}}
 class Data{String[] groups={"A","B","C","D","E","F","G","H","I","J","K","L"};ArrayList<String> teams=new ArrayList<>();ArrayList<Match> matches=new ArrayList<>();SharedPreferences sp;Data(Context c){sp=c.getSharedPreferences("scores",0);seed();load();}
 void seed(){String[][] g={{"Mexico","South Africa","Croatia","Korea Republic"},{"Canada","Switzerland","Qatar","TBD B4"},{"Brazil","Morocco","Scotland","TBD C4"},{"USA","Australia","Paraguay","TBD D4"},{"Germany","Ecuador","Ivory Coast","TBD E4"},{"Netherlands","Japan","Tunisia","TBD F4"},{"Belgium","Egypt","Norway","TBD G4"},{"Spain","Uruguay","Saudi Arabia","TBD H4"},{"France","Senegal","Iran","TBD I4"},{"Argentina","Austria","Algeria","TBD J4"},{"England","Colombia","Ghana","TBD K4"},{"Portugal","Denmark","Panama","TBD L4"}};String[] venues={"Mexico City","Toronto","Los Angeles","New York/New Jersey","Dallas","Miami","Vancouver","Atlanta","Houston","Kansas City","Boston","Seattle"};int day=11;for(int x=0;x<g.length;x++){String gr=groups[x];for(String t:g[x])teams.add(t);String[] t=g[x];matches.add(new Match(gr,t[0],t[1],"2026-06-"+(day+x%15),venues[x]));matches.add(new Match(gr,t[2],t[3],"2026-06-"+(day+1+x%15),venues[(x+3)%venues.length]));matches.add(new Match(gr,t[0],t[2],"2026-06-"+(day+6+x%12),venues[(x+6)%venues.length]));matches.add(new Match(gr,t[1],t[3],"2026-06-"+(day+7+x%12),venues[(x+8)%venues.length]));matches.add(new Match(gr,t[0],t[3],"2026-06-"+(day+12+x%7),venues[(x+9)%venues.length]));matches.add(new Match(gr,t[1],t[2],"2026-06-"+(day+12+x%7),venues[(x+10)%venues.length]));}Collections.sort(teams);} 
 void load(){for(int i=0;i<matches.size();i++){matches.get(i).homeGoals=sp.getInt("h"+i,-1);matches.get(i).awayGoals=sp.getInt("a"+i,-1);}} void save(){SharedPreferences.Editor e=sp.edit();for(int i=0;i<matches.size();i++){e.putInt("h"+i,matches.get(i).homeGoals);e.putInt("a"+i,matches.get(i).awayGoals);}e.apply();} void reset(){sp.edit().clear().apply();for(Match m:matches){m.homeGoals=-1;m.awayGoals=-1;}}
 Map<String,List<TeamRow>> standings(){Map<String,List<TeamRow>> out=new LinkedHashMap<>();for(String gr:groups){Map<String,TeamRow> m=new LinkedHashMap<>();for(Match ma:matches)if(ma.group.equals(gr)){m.putIfAbsent(ma.home,new TeamRow(gr,ma.home));m.putIfAbsent(ma.away,new TeamRow(gr,ma.away));if(ma.homeGoals>=0&&ma.awayGoals>=0){TeamRow h=m.get(ma.home),a=m.get(ma.away);h.gf+=ma.homeGoals;h.ga+=ma.awayGoals;a.gf+=ma.awayGoals;a.ga+=ma.homeGoals;if(ma.homeGoals>ma.awayGoals){h.w++;h.pts+=3;a.l++;}else if(ma.homeGoals<ma.awayGoals){a.w++;a.pts+=3;h.l++;}else{h.d++;a.d++;h.pts++;a.pts++;}}}ArrayList<TeamRow> list=new ArrayList<>(m.values());Collections.sort(list,(x,y)-> y.pts!=x.pts?y.pts-x.pts:((y.gf-y.ga)!=(x.gf-x.ga)?(y.gf-y.ga)-(x.gf-x.ga):y.gf-x.gf));out.put(gr,list);}return out;} List<TeamRow> bestThirds(){ArrayList<TeamRow> third=new ArrayList<>();for(List<TeamRow> l:standings().values())if(l.size()>2)third.add(l.get(2));Collections.sort(third,(x,y)-> y.pts!=x.pts?y.pts-x.pts:((y.gf-y.ga)!=(x.gf-x.ga)?(y.gf-y.ga)-(x.gf-x.ga):y.gf-x.gf));return third;} List<TeamRow> qualified(){ArrayList<TeamRow> q=new ArrayList<>();for(List<TeamRow> l:standings().values()){if(l.size()>0)q.add(l.get(0));if(l.size()>1)q.add(l.get(1));}List<TeamRow> th=bestThirds();for(int i=0;i<Math.min(8,th.size());i++)q.add(th.get(i));return q;}}
}
