package com.alensgarage.worldcupfan2026;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 int red=Color.rgb(200,16,46), dark=Color.rgb(139,0,24), bg=Color.rgb(247,247,247), text=Color.rgb(30,30,36); LinearLayout root,content,bottom; TextView title,sub; Data data; String screen="Home", myTeam="Croatia"; Handler h=new Handler();
 public void onCreate(Bundle b){super.onCreate(b);data=new Data(this);myTeam=getPreferences(0).getString("team","Croatia");build();showHome();}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);setContentView(root);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(18),dp(18),dp(18),dp(14));head.setBackgroundResource(getResources().getIdentifier("header_grad","drawable",getPackageName()));root.addView(head,new LinearLayout.LayoutParams(-1,dp(118)));title=tv("World Cup Fan 2026",25,Color.WHITE,1);title.setTypeface(Typeface.DEFAULT_BOLD);sub=tv("Offline tracker • Predictor • Groups • Knockout",13,Color.WHITE,1);head.addView(title);head.addView(sub);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(12),dp(12),dp(12));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.HORIZONTAL);bottom.setPadding(dp(4),dp(4),dp(4),dp(4));bottom.setBackgroundColor(Color.WHITE);root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(64)));nav("Home");nav("Matches");nav("Groups");nav("Predict");nav("More");}
 void nav(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setAllCaps(false);b.setOnClickListener(v->{ if(s.equals("Home"))showHome(); else if(s.equals("Matches"))showMatches(); else if(s.equals("Groups"))showGroups(); else if(s.equals("Predict"))showPredictor(); else showMore();});bottom.addView(b,new LinearLayout.LayoutParams(0,-1,1));}
 TextView tv(String s,int sp,int c,int lines){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);t.setPadding(dp(4),dp(2),dp(4),dp(2)); if(lines>0)t.setMaxLines(lines);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setBackgroundResource(getResources().getIdentifier("btn_red","drawable",getPackageName()));return b;}
 LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(14),dp(14),dp(14),dp(14));l.setBackgroundResource(getResources().getIdentifier("card_bg","drawable",getPackageName()));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(10));content.addView(l,lp);return l;}
 void clear(String h,String s){screen=h;title.setText(h);sub.setText(s);content.removeAllViews();}
 void showHome(){clear("World Cup Fan 2026","🔥 DARK MODE TEST BUILD v2.0 🔥");LinearLayout c=card();c.addView(tv("⚽ Kick-off countdown",19,text,1));TextView count=tv("",31,red,1);count.setTypeface(Typeface.DEFAULT_BOLD);c.addView(count);Runnable r=new Runnable(){public void run(){String d=daysTo("2026-06-11 21:00");
count.setText(d+" "+(d.equals("1")?"day":"days")+" to opening match");h.postDelayed(this,60000);}};r.run();LinearLayout c2=card();c2.addView(tv("⭐ My Team",19,text,1));c2.addView(tv(myTeam+" • next matches, group table and path to final",16,dark,2));Button b=btn("Open My Team");b.setOnClickListener(v->showMyTeam());c2.addView(b);LinearLayout c3=card();c3.addView(tv("🔥 Best selling feature",18,text,1));c3.addView(tv("Enter your own scores. The app calculates group standings, ranks 3rd placed teams, builds the knockout path and saves your prediction.",15,Color.DKGRAY,4));Button p=btn("Start Predictor");p.setOnClickListener(v->showPredictor());c3.addView(p);}
 String daysTo(String date){try{Date d=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).parse(date);long diff=d.getTime()-System.currentTimeMillis();return String.valueOf(Math.max(0,diff/86400000));}catch(Exception e){return "0";}}
 void showMatches(){clear("All Matches","104-match structure • filter mentally by group/team");for(Match m:data.matches){LinearLayout c=card();TextView a=tv(m.label(),16,text,3);a.setTypeface(Typeface.DEFAULT_BOLD);c.addView(a);c.addView(tv(m.date+" • "+m.venue+" • Group "+m.group,13,Color.GRAY,2));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);EditText h=edit(m.homeGoals), aw=edit(m.awayGoals);Button save=btn("Save");save.setOnClickListener(v->{m.homeGoals=getInt(h);m.awayGoals=getInt(aw);data.save();toast("Result saved");});row.addView(h,new LinearLayout.LayoutParams(0,dp(50),1));row.addView(aw,new LinearLayout.LayoutParams(0,dp(50),1));row.addView(save,new LinearLayout.LayoutParams(dp(90),dp(50)));c.addView(row);} }
 EditText edit(int val){EditText e=new EditText(this);e.setHint("-");e.setText(val>=0?""+val:"");e.setTextSize(18);e.setInputType(2);e.setGravity(17);return e;} int getInt(EditText e){try{return Integer.parseInt(e.getText().toString());}catch(Exception x){return -1;}}
 void showGroups(){clear("Groups","Automatic standings from entered results");Map<String,List<TeamRow>> map=data.standings();for(String g:data.groups){LinearLayout c=card();c.addView(tv("Group "+g,20,red,1));List<TeamRow> rows=map.get(g);for(int i=0;i<rows.size();i++){TeamRow r=rows.get(i);c.addView(tv((i+1)+". "+r.team+"  "+r.pts+" pts  "+r.gf+":"+r.ga+"  GD "+(r.gf-r.ga),15,text,1));}}
 LinearLayout c=card();c.addView(tv("Best third-placed teams",18,text,1));List<TeamRow> thirds=data.bestThirds();for(int i=0;i<thirds.size();i++)c.addView(tv((i+1)+". "+thirds.get(i).team+" (Group "+thirds.get(i).group+") • "+thirds.get(i).pts+" pts",14,i<8?red:Color.GRAY,1));}
 void showPredictor(){clear("Predictor","Fill scores, calculate tournament, save prediction");LinearLayout c=card();c.addView(tv("Your football bracket",20,text,1));c.addView(tv("1) Enter scores in Matches.\n2) Groups update automatically.\n3) Top 2 teams + best 8 third teams go through.\n4) Knockout screen shows the path.",15,Color.DKGRAY,5));Button m=btn("Enter Match Scores");m.setOnClickListener(v->showMatches());c.addView(m);Button k=btn("View Knockout");k.setOnClickListener(v->showKnockout());c.addView(k);
Button share=btn("Share My Prediction");
share.setOnClickListener(v->sharePrediction());
c.addView(share);Button reset=btn("Reset all scores");reset.setOnClickListener(v->{data.reset();showPredictor();});c.addView(reset);showGroupsPreview();}
 void showGroupsPreview(){LinearLayout c=card();c.addView(tv("Current qualified teams",18,text,1));List<TeamRow> q=data.qualified();for(int i=0;i<q.size();i++)c.addView(tv((i+1)+". "+q.get(i).team+" • Group "+q.get(i).group+" • "+q.get(i).pts+" pts",13,Color.DKGRAY,1));}
 void showKnockout(){clear("Knockout Bracket","Round of 32 to Final");List<TeamRow> q=data.qualified();String[] rounds={"Round of 32","Round of 16","Quarter-finals","Semi-finals","Final"};int idx=0, games=16;for(String r:rounds){LinearLayout c=card();c.addView(tv(r,20,red,1));for(int i=0;i<games;i++){String a= idx<q.size()?q.get(idx++).team:"TBD";String b= idx<q.size()?q.get(idx++).team:"TBD";c.addView(tv("⚽ "+a+" vs "+b,15,text,1));}games=Math.max(1,games/2);idx=0;}}
 void showMyTeam(){clear("My Team","Personalized fan hub");LinearLayout c=card();c.addView(tv("Selected team: "+myTeam,21,red,1));Spinner sp=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,data.teams);sp.setAdapter(ad);int pos=data.teams.indexOf(myTeam);if(pos>=0)sp.setSelection(pos);c.addView(sp);Button save=btn("Save My Team");save.setOnClickListener(v->{myTeam=sp.getSelectedItem().toString();getPreferences(0).edit().putString("team",myTeam).apply();toast("My Team saved");showMyTeam();});c.addView(save);LinearLayout c2=card();c2.addView(tv("Matches",18,text,1));for(Match m:data.matches)if(m.home.equals(myTeam)||m.away.equals(myTeam))c2.addView(tv(m.date+" • "+m.home+" vs "+m.away,14,Color.DKGRAY,2));LinearLayout c3=card();c3.addView(tv("Squad",18,text,1));c3.addView(tv("Player list module is ready. Add final tournament squads after official 26-player lists are published/verified. Use text only, no player photos.",14,Color.DKGRAY,5));}
 void showMore(){clear("More","Stats, settings, legal safety");LinearLayout c=card();Button a=btn("My Team");a.setOnClickListener(v->showMyTeam());c.addView(a);Button b=btn("Statistics");b.setOnClickListener(v->showStats());c.addView(b);Button k=btn("Knockout");k.setOnClickListener(v->showKnockout());c.addView(k);LinearLayout l=card();l.addView(tv("Store positioning",18,text,1));l.addView(tv("Independent fan-made app. No official FIFA logo, no official crests, no player photos, no live streaming. Works offline and lets fans build predictions.",14,Color.DKGRAY,5));}
 void showStats(){clear("Statistics","Calculated from entered results");int played=0,goals=0;Map<String,Integer> gf=new HashMap<>();for(Match m:data.matches)if(m.homeGoals>=0&&m.awayGoals>=0){played++;goals+=m.homeGoals+m.awayGoals;gf.put(m.home,gf.getOrDefault(m.home,0)+m.homeGoals);gf.put(m.away,gf.getOrDefault(m.away,0)+m.awayGoals);}LinearLayout c=card();c.addView(tv("Played matches: "+played,18,text,1));c.addView(tv("Goals: "+goals,18,text,1));String best="TBD";int max=-1;for(String t:gf.keySet())if(gf.get(t)>max){max=gf.get(t);best=t;}c.addView(tv("Best attack: "+best+" ("+Math.max(0,max)+")",18,red,1));}
 void sharePrediction(){
String msg="⚽ My World Cup Fan 2026 prediction\n\nMy team: "+myTeam+"\nQualified teams:";
java.util.List<TeamRow> q=data.qualified();
for(int i=0;i<Math.min(8,q.size());i++) msg+="\n"+(i+1)+". "+q.get(i).team;
msg+="\n\nMade with World Cup Fan 2026";
Intent send=new Intent(Intent.ACTION_SEND);
send.setType("text/plain");
send.putExtra(Intent.EXTRA_TEXT,msg);
startActivity(Intent.createChooser(send,"Share prediction"));
}
void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);} 
 static class Match{String group,home,away,date,venue;int homeGoals=-1,awayGoals=-1;Match(String g,String h,String a,String d,String v){group=g;home=h;away=a;date=d;venue=v;}String label(){return home+"  "+(homeGoals>=0?homeGoals:"-")+" : "+(awayGoals>=0?awayGoals:"-")+"  "+away;}}
 static class TeamRow{String group,team;int pts,gf,ga,w,d,l;TeamRow(String g,String t){group=g;team=t;}}
 class Data{String[] groups={"A","B","C","D","E","F","G","H","I","J","K","L"};ArrayList<String> teams=new ArrayList<>();ArrayList<Match> matches=new ArrayList<>();SharedPreferences sp;Data(Context c){sp=c.getSharedPreferences("scores",0);seed();load();}
 void seed(){String[][] g={{"Mexico","South Africa","Croatia","Korea Republic"},{"Canada","Switzerland","Qatar","TBD B4"},{"Brazil","Morocco","Scotland","TBD C4"},{"USA","Australia","Paraguay","TBD D4"},{"Germany","Ecuador","Ivory Coast","TBD E4"},{"Netherlands","Japan","Tunisia","TBD F4"},{"Belgium","Egypt","Norway","TBD G4"},{"Spain","Uruguay","Saudi Arabia","TBD H4"},{"France","Senegal","Iran","TBD I4"},{"Argentina","Austria","Algeria","TBD J4"},{"England","Colombia","Ghana","TBD K4"},{"Portugal","Denmark","Panama","TBD L4"}};String[] venues={"Mexico City","Toronto","Los Angeles","New York/New Jersey","Dallas","Miami","Vancouver","Atlanta","Houston","Kansas City","Boston","Seattle"};int day=11;for(int x=0;x<g.length;x++){String gr=groups[x];for(String t:g[x])teams.add(t);String[] t=g[x];matches.add(new Match(gr,t[0],t[1],"2026-06-"+(day+x%15),venues[x]));matches.add(new Match(gr,t[2],t[3],"2026-06-"+(day+1+x%15),venues[(x+3)%venues.length]));matches.add(new Match(gr,t[0],t[2],"2026-06-"+(day+6+x%12),venues[(x+6)%venues.length]));matches.add(new Match(gr,t[1],t[3],"2026-06-"+(day+7+x%12),venues[(x+8)%venues.length]));matches.add(new Match(gr,t[0],t[3],"2026-06-"+(day+12+x%7),venues[(x+9)%venues.length]));matches.add(new Match(gr,t[1],t[2],"2026-06-"+(day+12+x%7),venues[(x+10)%venues.length]));}Collections.sort(teams);} 
 void load(){for(int i=0;i<matches.size();i++){matches.get(i).homeGoals=sp.getInt("h"+i,-1);matches.get(i).awayGoals=sp.getInt("a"+i,-1);}}
 void save(){SharedPreferences.Editor e=sp.edit();for(int i=0;i<matches.size();i++){e.putInt("h"+i,matches.get(i).homeGoals);e.putInt("a"+i,matches.get(i).awayGoals);}e.apply();}
 void reset(){sp.edit().clear().apply();for(Match m:matches){m.homeGoals=-1;m.awayGoals=-1;}}
 Map<String,List<TeamRow>> standings(){Map<String,List<TeamRow>> out=new LinkedHashMap<>();for(String gr:groups){Map<String,TeamRow> m=new LinkedHashMap<>();for(Match ma:matches)if(ma.group.equals(gr)){m.putIfAbsent(ma.home,new TeamRow(gr,ma.home));m.putIfAbsent(ma.away,new TeamRow(gr,ma.away));if(ma.homeGoals>=0&&ma.awayGoals>=0){TeamRow h=m.get(ma.home),a=m.get(ma.away);h.gf+=ma.homeGoals;h.ga+=ma.awayGoals;a.gf+=ma.awayGoals;a.ga+=ma.homeGoals;if(ma.homeGoals>ma.awayGoals){h.w++;h.pts+=3;a.l++;}else if(ma.homeGoals<ma.awayGoals){a.w++;a.pts+=3;h.l++;}else{h.d++;a.d++;h.pts++;a.pts++;}}}ArrayList<TeamRow> list=new ArrayList<>(m.values());Collections.sort(list,(x,y)-> y.pts!=x.pts?y.pts-x.pts:(y.gf-y.ga)-(x.gf-x.ga)!=0?(y.gf-y.ga)-(x.gf-x.ga):y.gf-x.gf);out.put(gr,list);}return out;}
 List<TeamRow> bestThirds(){ArrayList<TeamRow> third=new ArrayList<>();for(List<TeamRow> l:standings().values())if(l.size()>2)third.add(l.get(2));Collections.sort(third,(x,y)-> y.pts!=x.pts?y.pts-x.pts:(y.gf-y.ga)-(x.gf-x.ga)!=0?(y.gf-y.ga)-(x.gf-x.ga):y.gf-x.gf);return third;}
 List<TeamRow> qualified(){ArrayList<TeamRow> q=new ArrayList<>();for(List<TeamRow> l:standings().values()){if(l.size()>0)q.add(l.get(0));if(l.size()>1)q.add(l.get(1));}List<TeamRow> th=bestThirds();for(int i=0;i<Math.min(8,th.size());i++)q.add(th.get(i));return q;}}
}
