package com.alensgarage.worldcupfan2026;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 int red=Color.rgb(213,0,45), red2=Color.rgb(150,0,30), gold=Color.rgb(255,204,0), text=Color.rgb(28,28,34), muted=Color.rgb(92,92,102), bg=Color.rgb(246,246,248), card=Color.WHITE, darkBg=Color.rgb(10,13,20), darkCard=Color.rgb(28,31,42), darkText=Color.rgb(238,241,247), darkMuted=Color.rgb(175,180,190);
 boolean darkMode=false; LinearLayout root,content,bottom; TextView title,sub; Data data; String myTeam="Croatia"; Handler h=new Handler(); String active="Home";
 public void onCreate(Bundle b){super.onCreate(b);data=new Data(this);SharedPreferences p=getPreferences(0);myTeam=p.getString("team","Croatia");darkMode=p.getBoolean("dark",false);build();showHome();}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);setContentView(root);header("World Cup Fan 2026","v3.0 • Premium offline tournament simulator");ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(12),dp(12),dp(88));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.HORIZONTAL);bottom.setPadding(dp(6),dp(6),dp(6),dp(6));root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(74)));applyTheme();nav("🏠","Home");nav("⚽","Matches");nav("🏆","Groups");nav("🔮","Predict");nav("⚙","More");}
 void header(String h,String s){LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(18),dp(20),dp(18),dp(14));head.setBackground(grad(red2,red));root.addView(head,new LinearLayout.LayoutParams(-1,dp(128)));title=tv(h,26,Color.WHITE,1);title.setTypeface(Typeface.DEFAULT_BOLD);sub=tv(s,13,Color.WHITE,2);head.addView(title);head.addView(sub);}
 void applyTheme(){bg=darkMode?darkBg:Color.rgb(246,246,248);card=darkMode?darkCard:Color.WHITE;text=darkMode?darkText:Color.rgb(28,28,34);muted=darkMode?darkMuted:Color.rgb(92,92,102);root.setBackgroundColor(bg);if(content!=null)content.setBackgroundColor(bg);if(bottom!=null)bottom.setBackgroundColor(darkMode?Color.rgb(17,20,30):Color.WHITE);}
 GradientDrawable grad(int a,int b){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{a,b});return g;}
 GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));g.setStroke(dp(1),darkMode?Color.rgb(58,63,78):Color.rgb(226,226,230));return g;}
 TextView tv(String s,int sp,int c,int lines){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);t.setPadding(dp(4),dp(3),dp(4),dp(3));if(lines>0)t.setMaxLines(lines);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setBackground(grad(red2,red));return b;}
 TextView chip(String s){TextView v=tv(s,13,darkMode?darkText:text,1);v.setGravity(17);v.setTypeface(Typeface.DEFAULT_BOLD);v.setBackground(round(darkMode?Color.rgb(34,38,50):Color.rgb(239,239,242),18));return v;}
 LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(14),dp(14),dp(14),dp(14));l.setBackground(round(card,24));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(12));content.addView(l,lp);return l;}
 void clear(String h,String s){active=h;title.setText(h);sub.setText(s);content.removeAllViews();applyTheme();refreshNav();}
 void nav(String ico,String label){TextView b=tv(ico+"\n"+label,12,muted,2);b.setGravity(17);b.setOnClickListener(v->{ if(label.equals("Home"))showHome(); else if(label.equals("Matches"))showMatches(""); else if(label.equals("Groups"))showGroups(); else if(label.equals("Predict"))showPredictor(); else showMore();});bottom.addView(b,new LinearLayout.LayoutParams(0,-1,1));}
 void refreshNav(){if(bottom==null)return;for(int i=0;i<bottom.getChildCount();i++){TextView v=(TextView)bottom.getChildAt(i);String s=v.getText().toString();boolean on=s.contains(active)||active.equals("World Cup Fan 2026")&&s.contains("Home")||active.equals("All Matches")&&s.contains("Matches")||active.equals("Predictor")&&s.contains("Predict");v.setTextColor(on?Color.WHITE:(darkMode?darkMuted:Color.rgb(50,50,55)));v.setTypeface(null,on?Typeface.BOLD:Typeface.NORMAL);v.setBackground(on?grad(red2,red):round(darkMode?Color.rgb(25,28,38):Color.rgb(237,237,240),18));}}
 void showHome(){clear("World Cup Fan 2026","v3.0 • Premium Predictor • Offline World Cup Simulator");LinearLayout hero=card();hero.addView(tv("🌍 WORLD CLASS BUILD v3.0",21,red,1));hero.addView(tv("Dark mode, search, flags, dream final, share prediction, premium screen and smarter fan hub are included.",14,muted,4));LinearLayout chips=new LinearLayout(this);chips.setOrientation(LinearLayout.HORIZONTAL);String[] cs={"Offline","No login","Predictor"};for(String x:cs){TextView c=chip(x);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(40),1);cp.setMargins(dp(3),dp(8),dp(3),0);chips.addView(c,cp);}hero.addView(chips);
 LinearLayout c=card();c.addView(tv("⚽ Kick-off countdown",19,text,1));TextView count=tv("",31,red,1);count.setTypeface(Typeface.DEFAULT_BOLD);c.addView(count);Runnable r=new Runnable(){public void run(){String d=daysTo("2026-06-11 21:00");count.setText(d+" "+(d.equals("1")?"day":"days")+" to opening");h.postDelayed(this,60000);}};r.run();
 LinearLayout c2=card();c2.addView(tv(flag(myTeam)+" My Team",20,text,1));c2.addView(tv(myTeam+" • next matches, group table and path to final",16,red2,2));Button b=btn("Open My Team");b.setOnClickListener(v->showMyTeam());c2.addView(b);
 LinearLayout c3=card();c3.addView(tv("🔥 Best selling feature",19,text,1));c3.addView(tv("Enter scores. The app calculates group standings, ranks best third-placed teams and builds the knockout path.",15,muted,4));Button p=btn("Start Predictor");p.setOnClickListener(v->showPredictor());c3.addView(p);}
 String daysTo(String date){try{Date d=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).parse(date);long diff=d.getTime()-System.currentTimeMillis();return String.valueOf(Math.max(0,diff/86400000));}catch(Exception e){return "0";}}
 void showMatches(String filter){clear("All Matches","Search by country, group, city or date");LinearLayout searchCard=card();EditText q=new EditText(this);q.setHint("Search matches, e.g. Croatia, Group A, Dallas");q.setText(filter);q.setSingleLine(true);q.setTextColor(text);q.setHintTextColor(muted);searchCard.addView(q,new LinearLayout.LayoutParams(-1,dp(52)));Button sb=btn("Search Matches");sb.setOnClickListener(v->{hideKeyboard(q);showMatches(q.getText().toString());});searchCard.addView(sb);
 String f=filter==null?"":filter.toLowerCase(Locale.US);for(Match m:data.matches){String hay=(m.home+" "+m.away+" "+m.group+" "+m.venue+" "+m.date).toLowerCase(Locale.US);if(f.length()>0&&!hay.contains(f))continue;LinearLayout c=card();TextView a=tv(flag(m.home)+" "+m.home+"  "+(m.homeGoals>=0?m.homeGoals:"-")+" : "+(m.awayGoals>=0?m.awayGoals:"-")+"  "+flag(m.away)+" "+m.away,16,text,3);a.setTypeface(Typeface.DEFAULT_BOLD);c.addView(a);c.addView(tv(m.date+" • "+m.venue+" • Group "+m.group,13,muted,2));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);EditText h=edit(m.homeGoals), aw=edit(m.awayGoals);Button save=btn("Save");save.setOnClickListener(v->{m.homeGoals=getInt(h);m.awayGoals=getInt(aw);data.save();toast("Result saved");});row.addView(h,new LinearLayout.LayoutParams(0,dp(52),1));row.addView(aw,new LinearLayout.LayoutParams(0,dp(52),1));row.addView(save,new LinearLayout.LayoutParams(dp(94),dp(52)));c.addView(row);}}
 EditText edit(int val){EditText e=new EditText(this);e.setHint("-");e.setText(val>=0?""+val:"");e.setTextSize(18);e.setInputType(2);e.setGravity(17);e.setTextColor(text);e.setHintTextColor(muted);return e;} int getInt(EditText e){try{return Integer.parseInt(e.getText().toString());}catch(Exception x){return -1;}}
 void showGroups(){clear("Groups","Automatic standings from entered results");Map<String,List<TeamRow>> map=data.standings();for(String g:data.groups){LinearLayout c=card();c.addView(tv("Group "+g,21,red,1));List<TeamRow> rows=map.get(g);for(int i=0;i<rows.size();i++){TeamRow r=rows.get(i);String mark=i<2?" ✅":(i==2?" 🟡":"");c.addView(tv((i+1)+". "+flag(r.team)+" "+r.team+mark+"  "+r.pts+" pts  "+r.gf+":"+r.ga+"  GD "+(r.gf-r.ga),15,text,1));}}LinearLayout c=card();c.addView(tv("Best third-placed teams",19,text,1));List<TeamRow> thirds=data.bestThirds();for(int i=0;i<thirds.size();i++)c.addView(tv((i+1)+". "+flag(thirds.get(i).team)+" "+thirds.get(i).team+" (Group "+thirds.get(i).group+") • "+thirds.get(i).pts+" pts",14,i<8?red:muted,1));}
 void showPredictor(){clear("Predictor","Build your full tournament path");LinearLayout c=card();c.addView(tv("🔮 Your football bracket",21,text,1));c.addView(tv("1) Enter scores in Matches.\n2) Groups update automatically.\n3) Qualified teams fill knockout.\n4) Share your prediction.",15,muted,5));Button m=btn("Enter Match Scores");m.setOnClickListener(v->showMatches(""));c.addView(m);Button k=btn("View Knockout Bracket");k.setOnClickListener(v->showKnockout());c.addView(k);Button d=btn("Dream Final");d.setOnClickListener(v->showDreamFinal());c.addView(d);Button share=btn("Share My Prediction");share.setOnClickListener(v->sharePrediction());c.addView(share);Button reset=btn("Reset all scores");reset.setOnClickListener(v->{data.reset();showPredictor();});c.addView(reset);showGroupsPreview();}
 void showGroupsPreview(){LinearLayout c=card();c.addView(tv("Current qualified teams",18,text,1));List<TeamRow> q=data.qualified();for(int i=0;i<Math.min(16,q.size());i++)c.addView(tv((i+1)+". "+flag(q.get(i).team)+" "+q.get(i).team+" • Group "+q.get(i).group+" • "+q.get(i).pts+" pts",13,muted,1));}
 void showKnockout(){clear("Knockout Bracket","Round of 32 → Final");List<TeamRow> q=data.qualified();String[] rounds={"Round of 32","Round of 16","Quarter-finals","Semi-finals","Final"};int games=16;for(String r:rounds){LinearLayout c=card();c.addView(tv("🏆 "+r,21,red,1));for(int i=0;i<games;i++){String a=(i*2)<q.size()?flag(q.get(i*2).team)+" "+q.get(i*2).team:"TBD";String b=(i*2+1)<q.size()?flag(q.get(i*2+1).team)+" "+q.get(i*2+1).team:"TBD";c.addView(tv("   ├─ "+a+"\n   └─ "+b,15,text,2));}games=Math.max(1,games/2);}}
 void showDreamFinal(){clear("Dream Final","Pick your dream World Cup finalists");LinearLayout c=card();c.addView(tv("🏟️ Build your dream final",21,text,1));Spinner a=new Spinner(this),b=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,data.teams);a.setAdapter(ad);b.setAdapter(ad);int pos=data.teams.indexOf(myTeam);if(pos>=0)a.setSelection(pos);b.setSelection(Math.min(5,data.teams.size()-1));c.addView(tv("Team A",13,muted,1));c.addView(a);c.addView(tv("Team B",13,muted,1));c.addView(b);TextView out=tv("",24,red,3);out.setTypeface(Typeface.DEFAULT_BOLD);Button make=btn("Create Dream Final");make.setOnClickListener(v->{String x=a.getSelectedItem().toString(),y=b.getSelectedItem().toString();out.setText(flag(x)+" "+x+" vs "+flag(y)+" "+y+"\nMy winner: "+flag(x)+" "+x);});c.addView(make);c.addView(out);}
 void showMyTeam(){clear("My Team","Personalized fan hub");LinearLayout c=card();c.addView(tv(flag(myTeam)+" Selected team: "+myTeam,21,red,1));Spinner sp=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,data.teams);sp.setAdapter(ad);int pos=data.teams.indexOf(myTeam);if(pos>=0)sp.setSelection(pos);c.addView(sp);Button save=btn("Save My Team");save.setOnClickListener(v->{myTeam=sp.getSelectedItem().toString();getPreferences(0).edit().putString("team",myTeam).apply();toast("My Team saved");showMyTeam();});c.addView(save);LinearLayout c2=card();c2.addView(tv("Matches",18,text,1));for(Match m:data.matches)if(m.home.equals(myTeam)||m.away.equals(myTeam))c2.addView(tv(m.date+" • "+flag(m.home)+" "+m.home+" vs "+flag(m.away)+" "+m.away,14,muted,2));LinearLayout c3=card();c3.addView(tv("Squad",18,text,1));c3.addView(tv("Final squads will be added after official tournament lists are published and verified. Text only. No player photos or protected logos.",14,muted,5));}
 void showMore(){clear("More","Settings, premium and legal safety");LinearLayout c=card();String[] names={"My Team","Statistics","Knockout","Dream Final",darkMode?"Switch to Light Mode":"Switch to Dark Mode","Premium / Pro Version","Share App"};for(String n:names){Button b=btn(n);b.setOnClickListener(v->{String x=((Button)v).getText().toString();if(x.startsWith("My"))showMyTeam();else if(x.startsWith("Statistics"))showStats();else if(x.startsWith("Knockout"))showKnockout();else if(x.startsWith("Dream"))showDreamFinal();else if(x.startsWith("Switch")){darkMode=!darkMode;getPreferences(0).edit().putBoolean("dark",darkMode).apply();showMore();}else if(x.startsWith("Premium"))showPremium();else shareApp();});c.addView(b);}LinearLayout l=card();l.addView(tv("Version 3.0",19,red,1));l.addView(tv("Independent fan-made app. No official FIFA logo, no official crests, no player photos, no live streaming. Offline simulator for fans.",14,muted,5));}
 void showPremium(){clear("Premium / Pro","Monetization-ready screen");LinearLayout c=card();c.addView(tv("🔥 Unlock Pro Predictor",24,red,1));c.addView(tv("Planned premium features:\n• Unlimited saved predictions\n• Share prediction as image\n• Advanced bracket simulation\n• Custom dream final\n• No ads option",16,text,7));Button b=btn("Coming soon: 1.99€");c.addView(b);}
 void showStats(){clear("Statistics","Calculated from entered results");int played=0,goals=0;Map<String,Integer> gf=new HashMap<>();for(Match m:data.matches)if(m.homeGoals>=0&&m.awayGoals>=0){played++;goals+=m.homeGoals+m.awayGoals;gf.put(m.home,gf.getOrDefault(m.home,0)+m.homeGoals);gf.put(m.away,gf.getOrDefault(m.away,0)+m.awayGoals);}LinearLayout c=card();c.addView(tv("Played matches: "+played,18,text,1));c.addView(tv("Goals: "+goals,18,text,1));String best="TBD";int max=-1;for(String t:gf.keySet())if(gf.get(t)>max){max=gf.get(t);best=t;}c.addView(tv("Best attack: "+flag(best)+" "+best+" ("+Math.max(0,max)+")",18,red,1));}
 void sharePrediction(){String msg="⚽ My World Cup Fan 2026 prediction\n\nMy team: "+flag(myTeam)+" "+myTeam+"\nQualified teams:";List<TeamRow> q=data.qualified();for(int i=0;i<Math.min(12,q.size());i++)msg+="\n"+(i+1)+". "+flag(q.get(i).team)+" "+q.get(i).team;msg+="\n\nMade with World Cup Fan 2026";shareText(msg,"Share prediction");}
 void shareApp(){shareText("⚽ Try World Cup Fan 2026 - offline predictor, groups and knockout simulator.","Share app");}
 void shareText(String msg,String title){Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_TEXT,msg);startActivity(Intent.createChooser(send,title));}
 void hideKeyboard(View v){try{((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);}catch(Exception e){}}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();} int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}
 String flag(String t){Map<String,String> f=new HashMap<>();f.put("Croatia","🇭🇷");f.put("Brazil","🇧🇷");f.put("Germany","🇩🇪");f.put("France","🇫🇷");f.put("Argentina","🇦🇷");f.put("England","🏴");f.put("Spain","🇪🇸");f.put("Portugal","🇵🇹");f.put("Netherlands","🇳🇱");f.put("Belgium","🇧🇪");f.put("Mexico","🇲🇽");f.put("USA","🇺🇸");f.put("Canada","🇨🇦");f.put("Japan","🇯🇵");f.put("Korea Republic","🇰🇷");f.put("Morocco","🇲🇦");f.put("Switzerland","🇨🇭");f.put("Denmark","🇩🇰");f.put("Uruguay","🇺🇾");f.put("Colombia","🇨🇴");f.put("Australia","🇦🇺");f.put("Qatar","🇶🇦");f.put("South Africa","🇿🇦");f.put("Scotland","🏴");f.put("Ecuador","🇪🇨");f.put("Ivory Coast","🇨🇮");f.put("Tunisia","🇹🇳");f.put("Egypt","🇪🇬");f.put("Norway","🇳🇴");f.put("Saudi Arabia","🇸🇦");f.put("Senegal","🇸🇳");f.put("Iran","🇮🇷");f.put("Austria","🇦🇹");f.put("Algeria","🇩🇿");f.put("Ghana","🇬🇭");f.put("Panama","🇵🇦");return f.containsKey(t)?f.get(t):"🌐";}
 static class Match{String group,home,away,date,venue;int homeGoals=-1,awayGoals=-1;Match(String g,String h,String a,String d,String v){group=g;home=h;away=a;date=d;venue=v;}String label(){return home+" "+(homeGoals>=0?homeGoals:"-")+" : "+(awayGoals>=0?awayGoals:"-")+" "+away;}}
 static class TeamRow{String group,team;int pts,gf,ga,w,d,l;TeamRow(String g,String t){group=g;team=t;}}
 class Data{String[] groups={"A","B","C","D","E","F","G","H","I","J","K","L"};ArrayList<String> teams=new ArrayList<>();ArrayList<Match> matches=new ArrayList<>();SharedPreferences sp;Data(Context c){sp=c.getSharedPreferences("scores",0);seed();load();}
 void seed(){String[][] g={{"Mexico","South Africa","Croatia","Korea Republic"},{"Canada","Switzerland","Qatar","TBD B4"},{"Brazil","Morocco","Scotland","TBD C4"},{"USA","Australia","Paraguay","TBD D4"},{"Germany","Ecuador","Ivory Coast","TBD E4"},{"Netherlands","Japan","Tunisia","TBD F4"},{"Belgium","Egypt","Norway","TBD G4"},{"Spain","Uruguay","Saudi Arabia","TBD H4"},{"France","Senegal","Iran","TBD I4"},{"Argentina","Austria","Algeria","TBD J4"},{"England","Colombia","Ghana","TBD K4"},{"Portugal","Denmark","Panama","TBD L4"}};String[] venues={"Mexico City","Toronto","Los Angeles","New York/New Jersey","Dallas","Miami","Vancouver","Atlanta","Houston","Kansas City","Boston","Seattle"};int day=11;for(int x=0;x<g.length;x++){String gr=groups[x];for(String t:g[x])if(!teams.contains(t))teams.add(t);String[] t=g[x];matches.add(new Match(gr,t[0],t[1],"2026-06-"+(day+x%15),venues[x]));matches.add(new Match(gr,t[2],t[3],"2026-06-"+(day+1+x%15),venues[(x+3)%venues.length]));matches.add(new Match(gr,t[0],t[2],"2026-06-"+(day+6+x%12),venues[(x+6)%venues.length]));matches.add(new Match(gr,t[1],t[3],"2026-06-"+(day+7+x%12),venues[(x+8)%venues.length]));matches.add(new Match(gr,t[0],t[3],"2026-06-"+(day+12+x%7),venues[(x+9)%venues.length]));matches.add(new Match(gr,t[1],t[2],"2026-06-"+(day+12+x%7),venues[(x+10)%venues.length]));}Collections.sort(teams);}
 void load(){for(int i=0;i<matches.size();i++){matches.get(i).homeGoals=sp.getInt("h"+i,-1);matches.get(i).awayGoals=sp.getInt("a"+i,-1);}}
 void save(){SharedPreferences.Editor e=sp.edit();for(int i=0;i<matches.size();i++){e.putInt("h"+i,matches.get(i).homeGoals);e.putInt("a"+i,matches.get(i).awayGoals);}e.apply();}
 void reset(){sp.edit().clear().apply();for(Match m:matches){m.homeGoals=-1;m.awayGoals=-1;}}
 Map<String,List<TeamRow>> standings(){Map<String,List<TeamRow>> out=new LinkedHashMap<>();for(String gr:groups){Map<String,TeamRow> m=new LinkedHashMap<>();for(Match ma:matches)if(ma.group.equals(gr)){m.putIfAbsent(ma.home,new TeamRow(gr,ma.home));m.putIfAbsent(ma.away,new TeamRow(gr,ma.away));if(ma.homeGoals>=0&&ma.awayGoals>=0){TeamRow h=m.get(ma.home),a=m.get(ma.away);h.gf+=ma.homeGoals;h.ga+=ma.awayGoals;a.gf+=ma.awayGoals;a.ga+=ma.homeGoals;if(ma.homeGoals>ma.awayGoals){h.w++;h.pts+=3;a.l++;}else if(ma.homeGoals<ma.awayGoals){a.w++;a.pts+=3;h.l++;}else{h.d++;a.d++;h.pts++;a.pts++;}}}ArrayList<TeamRow> list=new ArrayList<>(m.values());Collections.sort(list,(x,y)-> y.pts!=x.pts?y.pts-x.pts:(y.gf-y.ga)!=(x.gf-x.ga)?(y.gf-y.ga)-(x.gf-x.ga):y.gf-x.gf);out.put(gr,list);}return out;}
 List<TeamRow> bestThirds(){ArrayList<TeamRow> third=new ArrayList<>();for(List<TeamRow> l:standings().values())if(l.size()>2)third.add(l.get(2));Collections.sort(third,(x,y)-> y.pts!=x.pts?y.pts-x.pts:(y.gf-y.ga)!=(x.gf-x.ga)?(y.gf-y.ga)-(x.gf-x.ga):y.gf-x.gf);return third;}
 List<TeamRow> qualified(){ArrayList<TeamRow> q=new ArrayList<>();for(List<TeamRow> l:standings().values()){if(l.size()>0)q.add(l.get(0));if(l.size()>1)q.add(l.get(1));}List<TeamRow> th=bestThirds();for(int i=0;i<Math.min(8,th.size());i++)q.add(th.get(i));return q;}}
}